name: bio_env
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - r-base
  - jupyterlab
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - biopython
  - scikit-learn
  - r-ggplot2
  - r-dplyr
  - r-tidyverse
  - pip
  - pip:
      - openpyxl
      - plotly
      - kaleido
      - pillow
